teams = {
	'crd' : 'Arizona Cardinals',
	'atl' : 'Atlanta Falcons',
	'rav' : 'Baltimore Ravens',
	'buf' : 'Buffalo Bills',
	'car' : 'Carolina Panthers', 
	'chi' : 'Chicago Bear',
	'cin' : 'Cincinnati Bengals',
	'cle' : 'Cleveland Browns',
	'dal' : 'Dallas Cowboys',
	'den' : 'Denver Broncos',
	'det' : 'Detroit Lions',
	'gnb' : 'Green Bay Packers',
	'htx' : 'Houston Texans',
	'blt' : 'Indianapolis Colts',
	'jax' : 'Jacksonville Janguars',
	'kan' : 'Kansas City Chiefs',
	'mia' : 'Miami Dolphins',
	'min' : 'Minnesota Vikings',
	'nwe' : 'New England Patriots',
	'nor' : 'New Orleans Saints',
	'nyg' : 'New York Giants',
	'nyj' : 'New York Jets',
	'rai' : 'Oakland Raiders',
	'phi' : 'Philadelphia Eagles',
	'pit' : 'Pittsburgh Steelers',
	'sdg' : 'San Diego Chargers',
	'sfo' : 'San Francisco 49ers',
	'sea' : 'Seattle Seahawks',
	'ram' : 'Saint Louis Rams',
	'tam' : 'Tampa Bay Buccaneers',
	'oti' : 'Tennessee Titans',
	'was' : 'Washington Redskins'
}